---
title: "R Notebook"
output: html_notebook
---

Q1
```{r}
weather_forecast <- list(
          "Thursday"  = list(temp = 9, wind = 43, chance_rain = 58),
          "Friday"    = list(temp = 8, wind = 33, chance_rain = 53),
          "Saturday"    = list(temp = 8, wind = 27, chance_rain = 47)
          )
```
Q2
```{r}
  #could use weather_forecast[[1]][[3]] but easier as list is named
  weather_forecast$Thursday$chance_rain
  weather_forecast$Friday$wind
  weather_forecast$Thursday$temp
```

Q3.

```{r}
weather_matrix <- matrix(rep(0,14), nrow=2, ncol=7)
weather_matrix[1,1:7] <- c(9,8,8,6,6,7,8)
weather_matrix[2,1:7] <- c(8,7,6,7,8,8,9)
weather_matrix
```
Q4
```{r}
weather_matrix[2,3]
weather_matrix[2,]
weather_matrix[c(1:2),c(1,3,5)]
```
Q5
```{r}
add_prefix <-  function(x){
  if(is.character(x)){
    print(paste("The answer is",x))
    } else { 
    if(is.numeric(x)) {
      if(x>10) {
        print(x/10)
        } else {
        print(x)}
    } else {
    print("invalid input")}
    }
  }
```

Q6
```{r}
elemnt_check <- function(x,y) {
  if (is.vector(x) & is.vector(y)) 
  {
      if (length(x)==length(y)) 
      {
         if (sum(abs(sort(x)-sort(y))==0))   
          {
           if (sum(abs(x-y))==0)  
            {
            print("The same") 
            } else {
            print("Exactly the same")} 
            } else {
          print("Different Elements")}
      } else {
      print ("Different Length")}
  } else {
  print("Error: x and y must be vectors")}
}
```


```{r}
elemnt_check <- function(x,y) {
   if (is.vector(x) & is.vector(y)) 
   {
      if (length(x)==length(y)) 
      {
       
        if (sum(abs(x-y))==0)        
            {return("Exactly the same")} 
        else if (sum(abs(sort(x)-sort(y))==0))   
          {return("The same")} 
        else {("Different")}
        
        } else {
      print ("Different lengths")}
 } else {
 print("Error: x and y must be vectors")}
}
```


Q7

write code to print a multiplication table 


1. make an empty 12 x 12 matrix
2. loop through matrix

```{r}
m <- matrix(nrow=12,ncol=12)
```

 for (i in 1:nrow(m)){
   for `(j in 1:ncol(m){
   m[i,j] =  i*j}
 }
```


